Allow and Disallow setting  to create stand-alone debit note
agritheory/check_run pull request #232
Opened 2024-04-16 08:07 UTC by viralkansodiya

In Company I have added one field **Allow stand-alone debit notes?** where you can disable and enable functionality to create 
debit note stand-alone

If 'Allow stand-alone debit notes' is set to 'No,' then the 'is_return' checkbox in the purchase invoice will be hidden.

<img width="938" alt="show" src="https://github.com/agritheory/check_run/assets/141210323/d2c47928-aa9e-4fb0-b679-9e8054b809e4">

2024-04-29 10:36 UTC, viralkansodiya commented
@agritheory 
This configuration is also finished from my side, can you please check

2024-04-29 11:29 UTC, agritheory requested changes
This is missing the most critical feature - a check in `get_entries` that includes or exclude negative Purchase Invoices.

2024-04-29 11:29 UTC, agritheory commented on check_run/public/js/custom/purchase_invoice_custom.js
> +		frappe.model.get_value('Company', frm.doc.company, 'allow_stand_alone_debit_notes', r => {
Please move this field to Check Run Settings. I agree that it makes sense here and it would be the appropriate implementation if this were to be upstreamed into ERPNext.

2024-04-29 13:33 UTC, agritheory commented on check_run/public/js/custom/purchase_invoice_custom.js
> +		frm.trigger('stop_stand_alon_returns')
`stop_stand_alon_returns` => `stop_stand_alone_returns`

2024-04-30 11:59 UTC, viralkansodiya commented on check_run/public/js/custom/purchase_invoice_custom.js
> +		frappe.model.get_value('Company', frm.doc.company, 'allow_stand_alone_debit_notes', r => {
@agritheory I have updated the code please review

2024-05-08 23:08 UTC, agritheory approved these changes

2024-05-08 23:08 UTC, merged

2024-06-18 16:30 UTC, agritheory commented
@viralkansodiya Can you raise a PR for this feature on verison-15?

2024-06-19 05:16 UTC, viralkansodiya commented
> @viralkansodiya Can you raise a PR for this feature on verison-15?

@agritheory Okay